### ISSUE TITLE
Can't login "Bad login"

### ISSUE THREAD

**Issue by vv111y** [hidroh/materialistic#1042]
This has been for about a year now. No more information to go by. 
The credentials do work on the website.

**Comment by hidroh** [comment]
I may make a mistake while creating POST request body used for login. Do you happen to have any non-alphanumeric characters in username/password?

**Comment by vv111y** [comment]
No, just alphanumeric

**Comment by vv111y** [comment]
I don't even have that option, there was no account entry on the phone for Materialistic. 
1) I uninstalled and re-installed the app, still 'bad login'.
2) I created a new account (on website) with a different login name (profile user name has remained the same), now it works. Strange

**Comment by hidroh** [comment]
Hmm my suspect was that an account has been added, then password changed (via website) and the app failed to prompt for re-login, but apparently doesn't seem to be the case here.

Re saved stories: they are different, the app saved stories were released first (meant for save to read offline/bookmark) and then web favorites were released. Ideally they should sync up but since there are no public APIs for it I can't do it yet.

**Comment by vv111y** [comment]
That's too bad they don't offer the APIs for saving, that would make things much better. Regardless, this problem is resolved, closing. 

I also want to thank you for Materialistic, it is really well designed and is a pleasure to use. Much appreciated.
