### ISSUE TITLE
Vote up option shown also when I have already voted a post

### ISSUE THREAD

**Issue by aviaryan** [hidroh/materialistic#261]
Also there should be a marker to let users know which post they have already voted. 
If this its some API limitation, you can cache this data locally.

**Comment by hidroh** [comment]
It's by design. I can store voted items locally, but they will only contain items voted thru the app, not from all sources (e.g. via web or other devices), and there are no ways to get that information. In the end you will get only incomplete user data with no way to sync/converge, which may be worse than not having it at all.

I already compensate this by displaying animation and UI changes to notify users of immediate vote results, which will be cleared on refreshed (also by design). The voted items will get flushed out of the top pages within a day anyway.
