### ISSUE TITLE
"Use external browser" setting conflicts with "Default open" setting

### ISSUE THREAD

**Issue by robolange** [hidroh/materialistic#708]
In Settings / List, the option "Default open" defaults to Article. I would prefer that when I tap on a list item, it default to comments. I switch the setting to Comments. This has no visible effect, as tapping on list items still opens them in my external browser. If I disable Settings / Display / "Use external browser" the "Default open" correctly opens the comments.

"Default open" set to Comments should work correctly even if the user has elected to use an external browser.

**Comment by hidroh** [comment]
This has just been closed in #703. My rationale behind this is that you always have an option to open comments via comments button, and tapping the whole item would open the item (item screen if external browser disabled, or external browser otherwise).

If we follow what you suggest here then there is no discoverable way to open article for the case when both 'Use external browser' and 'Default open comments' are set (it's doable by tapping the header in the item page, but I doubt users notice it).

I can't think of a better UX to handle this case at the moment where both above settings are set.

**Comment by robolange** [comment]
Actually, what you describe (tapping the header in the item page to see the article) was exactly how I was expecting the feature to work. But I get what you are saying that some users won't figure that out.

I would propose that you have some kind of pop-up when the user has selected external browser and then selects Default open = Comments, or vice versa, to warn the user that these are incompatible features, and then reset the last selected option. This will prevent users like me from wasting time figuring out that it won't work, and then filing more bugs on it.

**Comment by hidroh** [comment]
I think I'll go with your original proposal, but adding a more explicit 'Article' button under the header.
